added changes to add admin page for managing app config
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #151
Opened 2021-11-04 18:18 UTC by santhoshb-msft

Admin page Icon
![image](https://user-images.githubusercontent.com/63607175/140396744-e0f7c886-274f-4738-9d57-fad000186838.png)

Manage App config

![image](https://user-images.githubusercontent.com/63607175/140396818-f04b7410-48d4-48dc-a85f-9a69480c713c.png)

Update App config

![image](https://user-images.githubusercontent.com/63607175/140396884-0b703824-4664-488c-8f03-5e92b59a5aa5.png)

2021-11-12 21:49 UTC, code4clouds requested changes
Minor changes where the styles are mixed with html, instead of the CSS

2021-11-12 21:49 UTC, code4clouds commented on src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/ApplicationConfigDetails.cshtml
> +                    <input class="cm-button-default mt0" type="button" style="background-color:#333" onclick="saveAppConfigDetails()" value="Save App Config" />
Background color belongs on the CSS

2021-11-12 21:49 UTC, code4clouds commented on src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/ApplicationConfigDetails.cshtml
> +            <div style="text-align:right;">
This belong in the CSS

2021-11-12 21:49 UTC, code4clouds commented on src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/Index.cshtml
> +        <div class="card-body" style="margin-left:-30px;">
style belong in the CSS

2021-11-12 21:49 UTC, code4clouds commented on src/SaaS.SDK.PublisherSolution/Views/Shared/_Layout.cshtml
> +            <div style="height:100%; font-weight:600">
Style belongs in the CSS

2021-11-12 21:51 UTC, code4clouds commented
@santhoshb-msft The password is visible on config... It should be hidden on view.  Use password field instead of textfied.

2021-12-07 08:19 UTC, santhoshb-msft commented on src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/ApplicationConfigDetails.cshtml
> +            <div style="text-align:right;">
moved styling to css file

2021-12-07 08:19 UTC, santhoshb-msft commented on src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/ApplicationConfigDetails.cshtml
> +                    <input class="cm-button-default mt0" type="button" style="background-color:#333" onclick="saveAppConfigDetails()" value="Save App Config" />
moved styling to css file

2021-12-07 08:20 UTC, santhoshb-msft commented on src/SaaS.SDK.PublisherSolution/Views/Shared/_Layout.cshtml
> +            <div style="height:100%; font-weight:600">
moved styling to css file

2021-12-07 08:20 UTC, santhoshb-msft commented on src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/Index.cshtml
> +        <div class="card-body" style="margin-left:-30px;">
moved styling to css file

2021-12-07 08:51 UTC, santhoshb-msft commented
> @santhoshb-msft The password is visible on config... It should be hidden on view. Use password field instead of textfied.

fixed SMTPpassword display to password . Still updatable!
![image](https://user-images.githubusercontent.com/63607175/144996931-90c89b33-a2c3-40cd-847d-dd344ef78dbd.png)
![image](https://user-images.githubusercontent.com/63607175/144996968-2e36d24c-397d-4f53-9682-b7c551877ec9.png)

2021-12-13 21:53 UTC, code4clouds requested changes
Just a question and two minor changes.

2021-12-13 21:53 UTC, code4clouds commented on src/SaaS.SDK.Client.DataAccess/Services/ApplicationConfigRepository.cs
> +            var existingConfig = this.context.ApplicationConfiguration.Where(a => a.Id == applicationConfiguration.Id).FirstOrDefault();
@santhoshb-msft What happen if the DB is empty and there is no record...  This will be null unless you define your default.   Line#57 will probably fail....

2021-12-13 21:53 UTC, code4clouds commented on src/SaaS.SDK.PublisherSolution/Views/Shared/_Layout.cshtml
> +    <link rel="stylesheet" href="~/css/Custom.css" />
To keep it with the current standard... let's use the small 'c'
rename the file to also use the small 'c'

2021-12-14 06:32 UTC, santhoshb-msft commented on src/SaaS.SDK.Client.DataAccess/Services/ApplicationConfigRepository.cs
> +            var existingConfig = this.context.ApplicationConfiguration.Where(a => a.Id == applicationConfiguration.Id).FirstOrDefault();
Currently the update doesnt support non existing/missing entries in the app config. If somehow happens then we have try catch to handle this.

2021-12-14 15:28 UTC, code4clouds commented
@santhoshb-msft  Did you change the name of the css filename as well?  Otherwise it will fail in Linux when referenced?

2021-12-14 16:04 UTC, code4clouds approved these changes

2021-12-14 16:04 UTC, merged