hotfix for per plan parameter
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #154
Opened 2021-11-10 21:44 UTC by msalemcode

In this hotfix, 
- Update ChangeQuantityAsync method to process changed Quantity instead of passing blanked PlanID
- Update webhook to process the change if it was triggered from other resources.

2021-11-12 21:05 UTC, code4clouds commented on src/SaaS.SDK.CustomerProvisioning/WebHook/WebhookHandler.cs
> +            var oldValue = this.subscriptionService.GetSubscriptionsBySubscriptionId(payload.SubscriptionId);
Use a more explicit variable name.... like currentQuantity?

2021-11-12 21:06 UTC, code4clouds commented on src/SaaS.SDK.CustomerProvisioning/WebHook/WebhookHandler.cs
> +                    NewValue = payload.Quantity.ToString(),
newValue can have a more explicit name... like updatedQuantity?

2021-11-12 21:07 UTC, code4clouds commented on src/SaaS.SDK.Client.DataAccess/Services/PlansRepository.cs
> +        private void CheckMeteredDimension(Plans planDetails, Plans existingPlan)
Function name needs to be call UpdateMeteredDimension as it does more than just checking, it also update the DB.

2021-11-12 21:42 UTC, code4clouds commented
@msalemcode - Just minor changes, but it looks good.

2021-11-12 21:44 UTC, code4clouds requested changes
Just minor changes...

2021-11-15 16:47 UTC, msalemcode commented on src/SaaS.SDK.CustomerProvisioning/WebHook/WebhookHandler.cs
> +            var oldValue = this.subscriptionService.GetSubscriptionsBySubscriptionId(payload.SubscriptionId);
Currently we can not change the name from oldValue since table SubscriptionAuditLogs expect variable oldValue and newValue

2021-11-16 15:03 UTC, msalemcode commented on src/SaaS.SDK.Client.DataAccess/Services/PlansRepository.cs
> +        private void CheckMeteredDimension(Plans planDetails, Plans existingPlan)
Currently we can not change the name from oldValue since table SubscriptionAuditLogs expect variable oldValue and newValue

2021-12-13 21:34 UTC, code4clouds approved these changes

2021-12-13 21:35 UTC, merged