Msalem/add scheduler function
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #232
Opened 2022-04-15 18:08 UTC by msalemcode

Adding new feature to schedule metered Emitting events. This PR will contain change to every application layer to reflect the newly added entity. Here is summary for changes

- SQL Server : Added 2 new tables + 1 new view for scheduler
- DAL : Added new entity to context and added contract and repository
- Business Service: Added Service and Model
- Publisher site: New View and controller for scheduler 
- New Function for scheduler

2022-05-18 19:49 UTC, code4clouds commented
@msalemcode  Would you attach screenshot of this features?

2022-05-19 19:42 UTC, tiffwchen commented
For ./docs/Installation-Instructions.md, please change the title from "Installating" to "Installing"

2022-05-19 22:28 UTC, tiffwchen requested changes

2022-05-19 22:28 UTC, tiffwchen commented on src/SaaS.SDK.Client.DataAccess/Services/MeteredDimensionsRepository.cs
> +
Remove this newline

2022-05-19 22:28 UTC, tiffwchen commented on src/SaaS.SDK.Client.DataAccess/Services/MeteredPlanSchedulerManagementRepository.cs
> +        /// <param name="context">The this.context.</param>
"The SaasKitContext" instead?

2022-05-20 20:04 UTC, olsoro0 commented on src/SaaS.SDK.PublisherSolution/Views/Home/Index.cshtml
> +                        <div class="programCardIcon5 wrap-win-icon-RecruitmentManagement">
I have a concern that scheduler and offers icons are similar which is not good for usability: 
![image](https://user-images.githubusercontent.com/97641588/169602724-c4c43d6f-a75d-4e7f-ad44-a887e1a2b0a6.png)
 Would it be possible to replace it with another bootstrap icon, for example such as 
![image](https://user-images.githubusercontent.com/97641588/169602913-7002198f-3552-4745-bbeb-4538ed46cf08.png)

2022-05-26 22:22 UTC, olsoro0 commented on src/SaaS.SDK.PublisherSolution/Views/Scheduler/NewScheduler.cshtml
> +                        <th>Scheduler Name&nbsp;&nbsp;</th>
can you add check for empty for schedule name?

2022-05-26 22:22 UTC, olsoro0 commented on src/SaaS.SDK.PublisherSolution/Views/Scheduler/NewScheduler.cshtml
> +                        <th>Scheduler Name&nbsp;&nbsp;</th>
can you add check for empty for schedule name?

2022-05-26 22:23 UTC, olsoro0 commented on src/SaaS.SDK.PublisherSolution/Views/Scheduler/NewScheduler.cshtml
> +                        <th>Quantity</th>
can you add check for 0 for quantity?

2022-05-26 22:23 UTC, olsoro0 commented on src/SaaS.SDK.PublisherSolution/Views/Scheduler/NewScheduler.cshtml
> +                        <th>Quantity</th>
can you add check for 0 for quantity?

2022-06-01 23:08 UTC, msalemcode commented on src/SaaS.SDK.MeteredTriggerJob/MeteredTriggerHelper.cs
> +                catch (MarketplaceException mex)
Not sure what do you mean here However this code is copy from existing code for Client SDK

2022-06-01 23:10 UTC, msalemcode commented on src/SaaS.SDK.MeteredTriggerJob/MeteredTriggerHelper.cs
> +                catch (MarketplaceException mex)
Added appropriate exception name

2022-06-01 23:38 UTC, msalemcode commented on src/SaaS.SDK.PublisherSolution/Views/Scheduler/NewScheduler.cshtml
> +                        <th>Quantity</th>
Add number input type

2022-06-07 18:46 UTC, tiffwchen approved these changes

2022-06-09 19:31 UTC, olsoro0 commented on src/SaaS.SDK.MeteredTriggerJob/SaaS.SDK.MeteredTriggerJob.csproj
> +    <TargetFramework>net6.0.300</TargetFramework>
This produces a non-blocking error during the accelerator installation:
"error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.300.  Either target .NET 6.0 or lower,
 or use a version of the .NET SDK that supports .NET 6.0.300."

2022-06-09 20:37 UTC, msalemcode commented on src/SaaS.SDK.MeteredTriggerJob/MeteredTriggerHelper.cs
> +        public static void PrintScheduler(SchedulerManagerViewModel item, DateTime? nextRun)
Please check latest version it will compile now

2022-06-09 22:34 UTC, tiffwchen approved these changes

2022-06-10 20:50 UTC, code4clouds requested changes

2022-06-10 20:50 UTC, code4clouds commented on src/SaaS.SDK.PublisherSolution/Views/Scheduler/NewScheduler.cshtml
> +    function validateDate()
Is this validation also done on the server side/function?

2022-06-10 20:50 UTC, code4clouds commented on .gitignore
> +src/SaaS.SDK.PublisherSolution/appsettings.Development.json
How this line different from 366?

2022-06-10 20:50 UTC, code4clouds commented on deployment/Database/AMP-DB-5.1.sql
> +    [Quantity]       FLOAT (53)   NOT NULL,
I thought we can only do uint in quantites...

2022-06-10 20:50 UTC, code4clouds commented on deployment/Templates/Deploy.ps1
> +if (!($MeteredSchedulerSupport))
Add a note to mentioned default behavior is to deploy meter scheduler.

2022-06-10 20:50 UTC, code4clouds commented on deployment/Templates/Deploy.ps1
> +    dotnet publish ..\..\src\SaaS.SDK.PublisherSolution\SaaS.SDK.PublisherSolution.csproj -c debug -o ..\..\Publish\PublisherPortal
Line 240 and 252 seems to be the same, bubble this up outside of the if statement to simplify maintenance.

2022-06-10 20:50 UTC, code4clouds commented on src/SaaS.SDK.PublisherSolution/Startup.cs
> +            services.AddDistributedMemoryCache();
Why are we adding session?

2022-06-10 20:50 UTC, code4clouds commented on src/SaaS.SDK.MeteredTriggerJob/MeteredTriggerHelper.cs
> +namespace MeteredTriggerHelper
This whole file has no comments

2022-06-13 17:54 UTC, olsoro0 commented on src/SaaS.SDK.PublisherSolution/Controllers/SchedulerController.cs
>                  schedulerUsageViewModel.Quantity = (decimal)SchedulerItem.Quantity;
Can you change Quantity to be an integer (not double) in the viewmodel and then remove this cast?

2022-06-14 22:16 UTC, olsoro0 commented on src/SaaS.SDK.PublisherSolution/Controllers/SchedulerController.cs
> +                schedulerUsageViewModel.FirstRunDate = SchedulerItem.StartDate.ToLocalTime();
Why did you change this to be local time? Should it be UTC?

2022-07-15 21:07 UTC, msalemcode commented on src/SaaS.SDK.PublisherSolution/Views/Scheduler/NewScheduler.cshtml
> +    function validateDate()
the date validation is on the client side beside there are validation built in the HTML 5 input itself

2022-07-15 21:42 UTC, code4clouds approved these changes

2022-07-15 21:42 UTC, code4clouds commented on docs/Installation-Instructions.md
> +git clone https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator.git -b 5.1.0 --depth 1; `
I will approve and change directly.

2022-07-15 21:44 UTC, merged