removed notstarted status
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #233
Opened 2022-04-18 17:50 UTC by santhoshb-msft

Removed unused NotStarted status.

2022-05-13 21:57 UTC, code4clouds commented
@santhoshb-msft  This may need a rebase..

2022-07-15 21:58 UTC, code4clouds requested changes
Need change... on the Enum.Try

2022-07-15 21:58 UTC, code4clouds commented on src/SaaS.SDK.Services/Services/SubscriptionService.cs
> +            SubscriptionStatusEnumExtension status;
This is missing the default value to return...

Try.Enum is usually inside an IF statement.  IF True returns the out, if False then dev needs to set the default value.   Ref the language spec: https://docs.microsoft.com/en-us/dotnet/api/system.enum.tryparse?view=net-6.0

2022-08-11 19:35 UTC, code4clouds commented on src/SaaS.SDK.Services/Services/SubscriptionService.cs
> +            SubscriptionStatusEnumExtension status;
@santhoshb-msft ... any ETA on this change?

2022-08-12 16:29 UTC, santhoshb-msft commented on src/SaaS.SDK.Services/Services/SubscriptionService.cs
> +            SubscriptionStatusEnumExtension status;
Done! @code4clouds

2022-08-12 21:31 UTC, code4clouds approved these changes

2022-08-12 21:31 UTC, merged