Starr - Simple text corrections and button placement
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #239
Opened 2022-05-05 23:36 UTC by dstarr

2022-05-06 15:17 UTC, code4clouds commented
@dstarr  Would you mind adding a picture of the changes?

2022-05-06 15:19 UTC, code4clouds commented on .gitignore
> +/src/SaaS.SDK.PublisherSolution/appsettings.Development.json
@dstarr  Did you mean to add the development files here?  Should we have instructions on how to apply the debug settings on it?

2022-05-06 17:54 UTC, dstarr commented on .gitignore
> +/src/SaaS.SDK.PublisherSolution/appsettings.Development.json
> @dstarr Did you mean to add the development files here? Should we have instructions on how to apply the debug settings on it?

Sorry, but I am not exactly sure what you mean. I removed this file from Git as it shouldn't be here. It should be ignored. As for why, the version that I found on the main branch had client secrets and app IDs in it because someone checked it in.

2022-05-06 17:57 UTC, dstarr commented
> @dstarr Would you mind adding a picture of the changes?

Added Go to Subscriptions list.
![image](https://user-images.githubusercontent.com/64742/167189840-eda10ef6-e92b-4d4a-afcc-267f5a9f923f.png)

Added message at the top of page.
![image](https://user-images.githubusercontent.com/64742/167190032-72eb1d56-775d-4bee-b7e8-5879e0943761.png)

2022-05-06 18:36 UTC, dstarr commented on .gitignore
> +/src/SaaS.SDK.PublisherSolution/appsettings.Development.json
Added dev appsettings file back with it also in .gitignore

2022-05-06 19:03 UTC, code4clouds approved these changes

2022-05-06 19:05 UTC, code4clouds commented
@dstarr There are some merging conflicts, you may need to take care of. :-/

2022-05-10 00:55 UTC, dstarr commented
> @dstarr There are some merging conflicts, you may need to take care of. :-/

Merge issues resolved.

2022-05-10 21:47 UTC, code4clouds commented on src/SaaS.SDK.PublisherSolution/Views/Home/ViewSubscriptionDetail.cshtml
> -                    @*<div class="row pr-3 pt-3 mt-5 pb-3 text-right" style="background-color:#F2F2F2">
@dstarr  Why is this block removed?

2022-05-12 17:45 UTC, dstarr commented
> If there are other errors we want the script to stop, right?
Correct.

2022-05-13 17:42 UTC, code4clouds requested changes

2022-05-13 17:42 UTC, code4clouds commented on src/SaaS.SDK.PublisherSolution/appsettings.Development.json
> +    "clientsecret": "M2JiYjU0NTgtMmQwOC00ODExLTllMzEtMDAwNmY4NTk0MDAw=",
@dstarr - You left your test env secrets.

2022-05-13 17:42 UTC, code4clouds commented on src/SaaS.SDK.CustomerProvisioning/appsettings.Development.json
> +    "defaultconnection": "Data Source=tcp:ecodesaasacc00.database.windows.net,1433;Initial Catalog=AMPSaaSDB;User Id=adminlogin@ecodesaasacc00.database.windows.net;Password=password21!!;"
@dstarr  - creds in here as well.

2022-05-13 17:42 UTC, code4clouds commented on src/SaaS.SDK.PublisherSolution/appsettings.Development.json
> +    "defaultconnection": "Data Source=tcp:ecodesaasacc00.database.windows.net,1433;Initial Catalog=AMPSaaSDB;User Id=adminlogin@ecodesaasacc00.database.windows.net;Password=password21!!;"
@dstarr  - creds here as well

2022-05-13 17:42 UTC, code4clouds commented on src/SaaS.SDK.CustomerProvisioning/appsettings.Development.json
> +    "clientsecret": "M2JiYjU0NTgtMmQwOC00ODExLTllMzEtMDAwNmY4NTk0MDAw=",
@dstarr Secret here too...

2022-05-13 20:01 UTC, dstarr commented
Moving these changes to smaller and more localized PRs.

2022-05-13 20:01 UTC, closed without merging