added admin page for email templates
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #261
Opened 2022-06-17 20:02 UTC by ms-mgrant

Most of the commits are cleaning up (reverting) the commits that I've moved to new branches.

2022-06-20 04:06 UTC, santhoshb-msft requested changes
Build is throwing an error. Could you please check.

2022-06-20 04:08 UTC, santhoshb-msft requested changes
![image](https://user-images.githubusercontent.com/63607175/174523522-4b655797-4982-4429-b99d-84a908179ec4.png)
 
Edit is throwing an error.

2022-06-21 03:18 UTC, santhoshb-msft commented on src/SaaS.SDK.Client.DataAccess/Services/EmailTemplateRepository.cs
> +        {
Could you please follow the similar save logic used by other repo please. This is sort of weekly typed.

2022-06-21 03:20 UTC, santhoshb-msft commented on src/SaaS.SDK.PublisherSolution/Controllers/ApplicationConfigController.cs
> +                return this.View("Error", ex);
Could you see if a generic error can be thrown.

2022-06-21 03:21 UTC, santhoshb-msft commented on src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/EmailTemplateDetails.cshtml
> +                        string[] editableFields = { "IsActive", "Subject", "Description", "TemplateBody" };
This is weekly typed, please use model properties to create form and also include to, cc and bcc as well please.

2022-06-21 03:23 UTC, santhoshb-msft commented on src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/EmailTemplates.cshtml
> +                                        <td>
fix the long spacing -> Description.

![image](https://user-images.githubusercontent.com/63607175/174709656-ce788de9-f6bc-4d0b-9f04-4bdab4c58d3a.png)

2022-06-21 22:44 UTC, santhoshb-msft commented on src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/EmailTemplateDetails.cshtml
> +                        <td class="text-left">@Html.TextAreaFor(model => model.TemplateBody, new { htmlAttributes = new { name="TemplateBody" } })</td>
Could you please add like a hint text "Due to the content size, it is recommended to copy the content to an external editor, modify the Template body, paste it back into here and save."

2022-06-22 17:02 UTC, ms-mgrant commented on src/SaaS.SDK.PublisherSolution/Controllers/ApplicationConfigController.cs
> +                return this.View("Error", ex);
Since I followed the format of the other exception handlers, the error page will always show the exception information instead of a generic message. How should I approach a custom error page/message?

2022-06-24 03:47 UTC, santhoshb-msft commented
@ms-mgrant  Looks like the change(bool? to bool) to go in the entities is again missing.
![image](https://user-images.githubusercontent.com/63607175/175458163-cc7cfe0b-192f-4a82-8167-c2fda748707d.png)

2022-06-29 21:00 UTC, santhoshb-msft approved these changes
changes look good.

2022-06-30 02:18 UTC, santhoshb-msft commented
Merging this. @code4clouds - please let me know if more needs to be done, we can take up a new item.

2022-06-30 02:19 UTC, merged

2022-07-15 22:44 UTC, code4clouds commented
@santhoshb-msft Just noticed your email templates...  It looks awesome! 🙌🏼