added logic to handle onetime payment schedule
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #324
Opened 2022-09-27 06:24 UTC by santhoshb-msft

added logic to handle onetime payment schedule

2022-10-11 03:54 UTC, santhoshb-msft commented
Need to update DB file

2022-10-20 15:09 UTC, code4clouds requested changes
"added logic to handle onetime payment schedule" - It seems you remove logic of current features, instead of just adding.

2022-10-20 15:09 UTC, code4clouds commented on deployment/Templates/Deploy.ps1
> -if ($MeteredSchedulerSupport -ne $true)
Are we making the meter scheduler permanent since we are removing this option?

2022-10-20 15:09 UTC, code4clouds commented on deployment/Database/AMP-DB.sql
> -IF NOT EXISTS (SELECT * FROM [dbo].[SchedulerFrequency] WHERE [Frequency] = 'Hourly')
If you are removing these frequencies, check with msalem to see what will be the impact.

2022-10-21 15:14 UTC, santhoshb-msft commented on deployment/Templates/Deploy.ps1
> -if ($MeteredSchedulerSupport -ne $true)
I believe that is correct, @msalemcode do you want to comment here.

2022-10-22 17:43 UTC, closed without merging