Offer Name in Subscriptions table
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #346
Opened 2022-11-03 23:56 UTC by alexdrenea

- Added Offer Name in the subcriptions table
- Added Offer / Plan Name in subscription details page

Customer Portal
- Added Offer name in the subscriptions table

Fixes #344

2022-11-04 00:29 UTC, code4clouds approved these changes

2022-11-04 00:30 UTC, code4clouds commented
Leave it to @santhoshb-msft  to 2nd approve and merge.

2022-11-18 21:52 UTC, santhoshb-msft requested changes
Please see my comments

2022-12-05 17:47 UTC, santhoshb-msft commented
@alexdrenea as we discussed are you going to close this and open a new PR?

2022-12-05 22:08 UTC, closed without merging