Feature/ef migrations
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #356
Opened 2022-11-12 17:12 UTC by alexdrenea

This PR enables the use of EF Migrations as a way to manage database changes.

**Database:**
- cleaned up SaaSKitContext (no changes)
- added initial migration
- added MigrationSeed as a way to programatically create the initial state of the db (stored procedures, initial data)

**Code:**
- Updated AdminSite to be able to start-up withouth error even if SaaSApiConfiguration is not provided (initialized with defaults). This is needed for migrations

**Scripts:**
- Removed deployment sql and bacpac as they are obsolete
- Split up `deploy.ps1` in 2 scripts: deploy -> deployes infrastructure only and deploy-code that is responsible for code deployment (admin portal, customer portal and database). This disconects infrastructure deployment (one-time) from code deployment (to enable code updates)
- Cleaned up the deployment folder now that there's no "Database" Folder needed.

**Documentation:**
- Updated install instructions (run both scripts on inital deploy), show options to update the codebase to a new accelerator version
- Updated readme for `DataAccess` to include instructions on how to use EF Migrations.
- Updated readme for the `deployment` folder with instructions on how to upgrade your installation.

2022-11-12 21:10 UTC, alexdrenea commented
@code4clouds @santhoshb-msft , for your review

2022-11-14 16:25 UTC, alexdrenea commented on src/AdminSite/Startup.cs
> +                ClientId = this.Configuration["SaaSApiConfiguration:ClientId"] ?? Guid.Empty.ToString(),
These changes are needed so that the App Compiles and starts-up without a "SaaSApiConfiguration" section. This allows migrations tooling to startup the app and connect to the database to exectute / read migrations.

2022-11-14 16:25 UTC, alexdrenea commented on src/DataAccess/Migrations/20221111162140_Initial.Designer.cs
> +﻿// <auto-generated />
This file is auto generated by the EF migrations tooling - Should not be changed

2022-11-14 16:25 UTC, alexdrenea commented on src/DataAccess/Migrations/20221111162140_Initial.cs
> +﻿using System;
this file is auto-generated by the EF migrations tooking ( updated the Up() method to run data seeding)

2022-11-14 16:25 UTC, alexdrenea commented on src/DataAccess/Migrations/SaasKitContextModelSnapshot.cs
> +﻿// <auto-generated />
This file is auto generated by the EF migrations tooling - Should not be changed

2022-11-16 18:50 UTC, santhoshb-msft requested changes

2022-11-16 18:54 UTC, alexdrenea commented on docs/Installation-Instructions.md
> +git clone https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator.git -b <branch-to-deploy> --depth 1; `
the backtick is required to signify a multi-line command in powershell

2022-11-16 18:56 UTC, alexdrenea commented on docs/Installation-Instructions.md
> +.\Deploy-Code.ps1 `
Interesting... my cloud shell had it installed. wonder if I installed it manually before? I will check again and add the install command if needed.

2022-11-16 20:21 UTC, alexdrenea commented on docs/Installation-Instructions.md
> +.\Deploy-Code.ps1 `
addressed - added line item to install dotnet ef toolset if missing

2022-11-16 20:21 UTC, alexdrenea commented on src/DataAccess/Migrations/20221111162140_Initial.cs
> +using Microsoft.EntityFrameworkCore.Migrations;
thank you! good catch! Fixed!

2022-11-30 05:28 UTC, santhoshb-msft commented
@alexdrenea - new install works great.
Running an upgrade on 6.0.1 doesnt work, Could you please look into. thanks!

2022-12-01 02:35 UTC, santhoshb-msft approved these changes
All looking good

1.  Did code review
2. DB compare against old and new db
3. 
![image](https://user-images.githubusercontent.com/63607175/204952121-b9f28a06-33d0-4c8c-824f-6c94a4a0e22f.png)
4. Performed fresh copy deployment
5. Performed a upgrade deployment from 6.0.1 to current version

2022-12-01 02:36 UTC, merged