Added selenium tests bootstrapping
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #414
Opened 2022-12-16 07:13 UTC by santhoshb-msft

Added selenium tests bootstrapping

2022-12-21 15:30 UTC, santhoshb-msft commented
This is a draft PR to show whats coming. Will build a new PR on UI tests once the tests folder structure PR is merged

2022-12-21 23:01 UTC, dstarr requested changes
I know you knwo this, but after getting the tests to run, please:

Create 2 projects for these tests
- AdminSite.Test.Ui
- CustomerSite.Test.Ui

The Services project has no UI

Really like this first stab at UI testing!

2022-12-21 23:08 UTC, santhoshb-msft commented on src/Services.Test.Ui/AdminApplicationShould.cs
> +        driver.FindElement(By.Id("idSIButton9")).SendKeys(Keys.Enter);
![image](https://user-images.githubusercontent.com/63607175/209020199-5dc17ca1-6771-4aca-8c24-f5d20085b57d.png)
 Works for me @dstarr

2023-01-30 04:51 UTC, santhoshb-msft commented on src/Services.Test.Ui/AdminApplicationShould.cs
> +        driver.FindElement(By.Id("idSIButton9")).SendKeys(Keys.Enter);
@dstarr I believe we resolve this in our offline conversation.

2023-01-30 04:51 UTC, closed without merging