Msalem/add email scheduler
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #470
Opened 2023-04-11 18:33 UTC by msalemcode

This PR add enhancement to notification system to include scheduler notification
Customer will have abilities to enable or disable the notification

1- New App Configuration setting added
2- Add new scheduler email template
3- Add new Email Helper for email

2023-04-11 19:47 UTC, code4clouds requested changes

2023-04-11 19:47 UTC, code4clouds commented on src/MeteredTriggerJob/MeteredTriggerHelper.cs
> +/*        schedulerService = new MeteredPlanSchedulerManagementService(frequencyRepository,
Why is this commented out?  If its not needed, delete it...

2023-04-11 19:47 UTC, code4clouds commented on src/MeteredTriggerJob/MeteredTriggerHelper.cs
> +    private IEmailTemplateRepository emailTemplateRepository;
Should these repositories be readonly as well?

2023-04-11 19:47 UTC, code4clouds commented on src/MeteredTriggerJob/MeteredTriggerHelper.cs
>              Console.WriteLine(ex.Message);
Should we send this to the application logs using the log service for the admin to read them later on the page?

2023-04-11 19:47 UTC, code4clouds commented on src/Services/Helpers/EmailHelper.cs
> +    public EmailContentModel PrepareMeteredEmailContent(string schedulerTaskName, String subscriptionName, string subscriptionStatus, string responseJson)
Why not use the current mail service?  It has all this already initialized.

2023-04-15 02:04 UTC, msalemcode commented on src/Services/Helpers/EmailHelper.cs
> +    public EmailContentModel PrepareMeteredEmailContent(string schedulerTaskName, String subscriptionName, string subscriptionStatus, string responseJson)
The current mail service depends on EmailHelper to proved an emailContentmodel object. I am using this method to get the emilcontent then pass it to current initialized mail service.

2023-04-15 02:05 UTC, msalemcode commented on src/MeteredTriggerJob/MeteredTriggerHelper.cs
>              Console.WriteLine(ex.Message);
This is a good idea I should look into implementing it

2023-04-18 03:29 UTC, santhoshb-msft commented on src/DataAccess/Migrations/Custom/BaselineV6_Seed.cs
> +INSERT [dbo].[ApplicationConfiguration] ( [Name], [Value], [Description]) VALUES ( N'EnablesSuccessfulSchedulerEmail', N'False', N'This will enable sending email for successful mertered usage.')
@msalemcode  two things.
1. should we use email template table for this?
2. does this work if its in this this file for folks to upgrade from current 6.0?

2023-05-23 01:52 UTC, alexdrenea commented on deployment/Upgrade.ps1
> +	        VALUES (N'20221118045814_Baseline_v2', N'6.0.1'), (N'20221118203340_Baseline_v5', N'6.0.1'), (N'20221118211554_Baseline_v6', N'6.0.1'), (N'20230521211554_Baseline_v7', N'6.0.1');
this is not needed.
This is only needed to apply migrations pre Entity Framework (where we didn't have the automatic DB versioning provided by EF)

2023-05-23 01:52 UTC, alexdrenea commented on src/MeteredTriggerJob/MeteredTriggerHelper.cs
>              Console.WriteLine(ex.Message);
I agree. but it should be part of a separate "logging" related PR ?

2023-05-23 01:52 UTC, alexdrenea commented on src/MeteredTriggerJob/MeteredTriggerHelper.cs
> +        Console.WriteLine($"Item Id: {item.Id} \n\r" +
Use Environment.NewLine instead of "\n\r". This won't work properly on Linux

2023-05-23 01:52 UTC, alexdrenea commented on src/DataAccess/Migrations/Custom/BaselineV7_Seed.cs
> +INSERT [dbo].[ApplicationConfiguration] ( [Name], [Value], [Description]) VALUES ( N'EnablesSuccessfulSchedulerEmail', N'False', N'This will enable sending email for successful mertered usage.')
typo: "metered" no "mertered"

2023-06-23 15:48 UTC, code4clouds commented on src/MeteredTriggerJob/MeteredTriggerHelper.cs
>                      else if (timeDifferentInHours < 0)
This else if is blank...  it should be removed if not necessary.

2023-06-23 15:52 UTC, code4clouds requested changes
a few minor requests... almost there.

2023-06-23 15:52 UTC, code4clouds commented on src/MeteredTriggerJob/MeteredTriggerHelper.cs
>          switch (frequency)
I dont understand this one... Is this switch always going to return null?

2023-06-23 15:52 UTC, code4clouds commented on src/MeteredTriggerJob/MeteredTriggerHelper.cs
>                      else if (timeDifferentInHours < 0)
or comment to understand why is this empty.

2023-07-13 16:18 UTC, santhoshb-msft commented
@msalemcode please see if you can resolve the comments and move it over to @code4clouds

2023-07-20 16:38 UTC, closed without merging