Added new properties to the Subscriptions table
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #549
Opened 2023-09-12 14:26 UTC by alexdrenea

- OfferId (Name) and Term details (Name, StartDate, EndDate)
- Updated subscriptions page both admin and customer to show OfferName
- Updated subscriptions details page to show term details

2023-09-22 17:13 UTC, santhoshb-msft commented on src/DataAccess/Migrations/20230912052848_SubscriptionDetails.cs
@alexd would it be possible to name these files ending with _v714 to denote the future version please?

2023-09-25 01:47 UTC, alexdrenea commented on src/DataAccess/Migrations/20230912052848_SubscriptionDetails.cs
done, renamed to _v740

2023-09-27 05:51 UTC, santhoshb-msft requested changes
Thank you for making the migration and Ui changes. 
@alexdrenea could you please merge your branch from main latest.

2023-09-29 03:24 UTC, santhoshb-msft approved these changes
verified in both new and upgrade scenarios.

2023-09-29 03:25 UTC, santhoshb-msft commented on src/DataAccess/Migrations/20230912052848_SubscriptionDetails.cs
thank you @alexdrenea

2023-09-29 03:25 UTC, merged