Bootstrap 5.3.0
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #551
Opened 2023-09-18 16:37 UTC by neelavarshad

Changed bootstrap version from 4.4.1 to 5.3.0

Review deployment and check all flows

2023-09-29 05:20 UTC, santhoshb-msft requested changes
Hi @neelavarshad could you merge latest from main and resolve conflicts

2023-09-29 22:48 UTC, neelavarshad commented
@santhoshb-msft Merged and resolved

2023-09-29 22:49 UTC, santhoshb-msft commented
> @santhoshb-msft Merged and resolved

Thank you @neelavarshad

2023-10-02 05:48 UTC, santhoshb-msft commented
@neelavarshad some initial observations below

Admin page issues:

- Logo
- Menu notworking when minimized
- buttons alignment to right (details/activate page)
- Plans page tabs not working
- Email templates action not working
- Appsettings button gap
- Cookies title
- Fetch all moved
- Table alignment
- Offer page - space on the top.
- App config action not working.


Landing page: Yet to test

2023-10-19 01:08 UTC, neelavarshad commented
- [ ] - Logo
- [ ] - Menu notworking when minimized
- [ ] - buttons alignment to right (details/activate page)
- [ ] - Plans page tabs not working
- [ ] - Email templates action not working
- [ ] - Appsettings button gap
- [ ] - Cookies title
- [ ] - Fetch all moved
- [ ] - Table alignment
- [ ] - Offer page - space on the top.
- [ ] - App config action not working.

2023-11-10 00:24 UTC, santhoshb-msft commented on src/CustomerSite/wwwroot/js/site.js
no changes here right?

2023-11-10 00:25 UTC, santhoshb-msft requested changes
@neelavarshad almost looks good with some imperfections in the UI which I will share directly with you. things like alignment and some button functionalities.

2023-11-10 00:26 UTC, santhoshb-msft commented
@neelavarshad  once you are done with the changes, please assign the PR to me

2023-12-14 01:33 UTC, neelavarshad commented
@santhoshb-msft Assigned the PR back to you. 
I have changed the UI per your comments. There was a missing screenshot for Change quantity, but I think you meant to showcase left alignment. I have made that change but let me know if there's anything else. Thanks!

2023-12-15 20:21 UTC, santhoshb-msft reviewed
a couple of code comments below and some ui changes suggested on the internal chat

2023-12-15 20:21 UTC, santhoshb-msft commented on src/CustomerSite/CustomerSite.csproj
> +    <Compile Remove="wwwroot\lib\bootstrap\4.4.1\**" />
should we remove this?

2023-12-16 00:07 UTC, neelavarshad commented on src/CustomerSite/CustomerSite.csproj
> +    <Compile Remove="wwwroot\lib\bootstrap\4.4.1\**" />
This is just a compile/build file. I don't think we should overwrite anything here. Right?

2023-12-16 00:09 UTC, neelavarshad commented
@santhoshb-msft  Pushed additional changes and assigned back to you. Thanks!

2023-12-19 05:24 UTC, santhoshb-msft reviewed
comment inline

2023-12-19 05:24 UTC, santhoshb-msft commented on src/AdminSite/Views/Shared/_Layout.cshtml
> +    <link href="~/lib/Datatable/css/responsive.bootstrap.min.css" rel="stylesheet" />
Can you verify why we need this. I dont find them in the lib folder

2023-12-19 17:53 UTC, neelavarshad commented on src/AdminSite/Views/Shared/_Layout.cshtml
> +    <link href="~/lib/Datatable/css/responsive.bootstrap.min.css" rel="stylesheet" />
@santhoshb-msft  The 4.4.1 references are after the delete. Once merged, you won't see it. I've also unreferenced unused  Datatable stylesheet references. Thanks!

2023-12-19 17:53 UTC, neelavarshad commented
Changes to landing page with Change quantity button added.

2023-12-19 23:52 UTC, santhoshb-msft approved these changes
tested with new installation and upgrade scenarios. 
All commented fixed by @neelavarshad 

Approving

2023-12-19 23:52 UTC, merged