Fix last run task
Azure/Commercial-Marketplace-SaaS-Accelerator pull request #581
Opened 2023-10-24 00:10 UTC by msalemcode

Change the scheduler task list to return items expected to execute and ignore items already executed.

2023-10-24 17:48 UTC, code4clouds requested changes
Code changes need around memory allocaiton and performance.

2023-10-24 17:48 UTC, code4clouds commented on src/Services/Services/MeteredPlanSchedulerManagementService.cs
> +        var allSchedulerViewData = this.schedulerViewRepository.GetAll().OrderBy(s => s.AMPSubscriptionId);
Wouldn't it be better to sort it with the dates closest to the current time, so they execute closer together and help avoid missing the window?

2023-10-24 17:48 UTC, code4clouds commented on src/Services/Services/MeteredPlanSchedulerManagementService.cs
> +        var allSchedulerViewData = this.schedulerViewRepository.GetAll().OrderBy(s => s.AMPSubscriptionId);
this should be a const to avoid alteration and increase performance.

2023-10-24 17:48 UTC, code4clouds commented on src/Services/Services/MeteredPlanSchedulerManagementService.cs
> +            if (!CheckIfSchedulerRun(item.Id, item.SchedulerName))
The IF should be under the foreach then if TRUE assign values then add to the list.  Adding the values first then throwing them away if the condition is not met waste allocation time and impact performance.   

In other words the allocation to the list should be done only after the condition is met.

2023-10-25 01:18 UTC, msalemcode commented on src/Services/Services/MeteredPlanSchedulerManagementService.cs
> +        var allSchedulerViewData = this.schedulerViewRepository.GetAll().OrderBy(s => s.AMPSubscriptionId);
Update to sort by start date

2023-10-27 22:39 UTC, code4clouds approved these changes

2023-10-29 16:37 UTC, merged